# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd2aee0ca0fc0706cb686b11482bece274dfba964d0f83ed9265395e6c2620be7d30b0893ecd7d03dc97da66625a954d4c7783ed06f75819ba560dc74b97930

test:
  secret_key_base: 38d9f9f5f478b5b8430463d6ac2eba8a3c805a27f48c527fa34a4918c6fe2d83560a6449556c84c9ed4eabca8535384f7a181991036f407485834e5c54ffc65f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
